language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
branches:
  only:
    - /^7.x/
before_install:
  - export ISLANDORA_DIR=$TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/drupal/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
script:
  - ant -buildfile sites/all/modules/islandora/drupal/islandora/build.xml lint
  - $ISLANDORA_DIR/drupal/islandora/tests/scripts/line_endings.sh sites/all/modules/islandora/drupal/islandora sites/all/modules/islandora/drupal/islandora_basic_image /islandora sites/all/modules/islandora/drupal/islandora_collection sites/all/modules/islandora/drupal/islandora_dc sites/all/modules/islandora/drupal/islandora_mods
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora islandora_basic_image islandora_collection islandora_dc islandora_mods
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora/drupal/islandora sites/all/modules/islandora/drupal/islandora_basic_image sites/all/modules/islandora/drupal/islandora_collection sites/all/modules/islandora/drupal/islandora_dc sites/all/modules/islandora/drupal/islandora_mods
  - drush test-run --uri=http://localhost:8081 Islandora
