language: php
php:
  - 5.3.3
  - 5.4
branches:
  only:
    - 7.x
env:
  - FEDORA_VERSION="3.5"
before_install:
  - export ISLANDORA_DIR=$TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/tests/travis_setup.sh
  - cd $HOME/drupal-*
script:
  - ant -buildfile sites/all/modules/islandora/build.xml lint
  - drush dcs sites/all/modules/islandora
  - phpcpd sites/all/modules/islandora
  - drush test-run --uri=http://localhost:8081 Islandora
