language: php
php:
  - 5.3
before_script:
  - mysql -u root -e 'create database drupal;'
  - mysql -u root -e "create database fedora;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON fedora.* To 'fedora'@'localhost' IDENTIFIED BY 'fedora';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON drupal.* To 'drupal'@'localhost' IDENTIFIED BY 'drupal';"
  - git clone git://github.com/Islandora/islandora_tomcat.git
  - cd islandora_tomcat
  - export CATALINA_HOME='.'
  - ./bin/startup.sh
  - cd ..
  - pyrus channel-discover pear.drush.org
  - pyrus install drush/drush
  - phpenv rehash
  - drush dl --yes drupal
  - cd drupal-*
  - drush si standard --db-url=mysql://drupal:drupal@localhost/drupal --yes
  - drush en --yes simpletest
  - drush cc all
  - drush runserver --server=builtin 80 &
  - sleep 4
  - drush vset --yes simpletest_verbose FALSE
script: 
  - drush test-run Syslog --xml --uri=http://127.0.0.1:8080
