site_name: Islandora
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora-labs/islandora

use_absolute_urls: true

#include_search: true

theme: bootstrap

pages:

# Introduction
  - ['index.md', 'About', 'Islandora']
  - ['camel/sync/README.md', 'About', 'Islandora-Sync']
  - ['drupal/islandora/README.md', 'About', 'Islandora (Drupal module)']

# Installation:
  - ['install/README.md', 'Installation', 'Vagrant']

# Contributing
  - ['contributing/contributing.md', 'Contributing', 'How to contribute']

# Technical Documentation
  - ['technical-documentation/architecture.md', 'Technical Documentation', 'Architecture']
  - ['technical-documentation/services.md', 'Technical Documentation', 'Middleware Services']
  - ['technical-documentation/commands.md', 'Technical Documentation', 'Commands']
  - ['technical-documentation/migration.md', 'Technical Documentation', 'Migration']
  - ['technical-documentation/docs-build.md', 'Technical Documentation', 'How to build documenation']
