site_name: Islandora
site_dir: site
site_description: Documentation for Islandora

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora-labs/islandora

docs_dir: sources
  
use_absolute_urls: true

#include_search: true

theme: bootstrap

pages:

# Introduction
  - ['index.md', 'About', 'Islandora']
  - ['camel/sync/README.md', 'About', 'Islandora-Sync']
  - ['drupal/islandora/README.md', 'About', 'Islandora (Drupal module)']

# Installation:
  - ['install/README.md', 'Installation', 'Vagrant']

# Contributing
  - ['contributing/contributing.md', 'Contributing', 'How to contribute']

# Technical Documentation
  - ['technical-documentation/technical_design.md', 'Technical Documentation', 'Technical Design']
